Fix Multiple Folder Check in bin

diff --git a/sortnet/bin/worker b/sortnet/bin/worker
--- a/sortnet/bin/worker
+++ b/sortnet/bin/worker
@@ -7,37 +7,32 @@ shift
 inputdirs=()
 outputdir=""
 input_data_type="byte"  # Valeur par défaut
-while :
-do
-    case "$1" in
-      -ascii)
-            input_data_type="ascii"
-            shift;;
-      -I | --input)
-          shift
-          while :
-          do
-              case "$1" in
-                "") break;;
-                -*) break;;
-                *) inputdirs+=( "$1" ) ; shift;;
-              esac
-          done;;
-      -O | --output)
-          shift
-          while :
-          do
-              case "$1" in
-                "") break;;
-                -*) break;;
-                *) outputdir="$1"; shift; break;;
-              esac
-          done;;
-      -*)
-          echo "Error: Unknown option: $1" >&2; exit 1;;
-      *)
-          break;;
-    esac
+while [ "$#" -gt 0 ]; do
+  case "$1" in
+    -ascii)
+      input_data_type="ascii"
+      shift;;
+    -I | --input)
+      shift
+      while [ "$#" -gt 0 ] && [ "${1:0:1}" != "-" ]; do
+        inputdirs+=( "$1" )
+        shift
+      done;;
+    -O | --output)
+      shift
+      if [ "$#" -gt 0 ] && [ "${1:0:1}" != "-" ]; then
+        outputdir="$1"
+        shift
+      else
+        echo "Error: Missing argument for output directory" >&2
+        exit 1
+      fi;;
+    -*)
+      echo "Error: Unknown option: $1" >&2
+      exit 1;;
+    *)
+      break;;
+  esac
 done
 
 if [ "${#inputdirs[@]}" -lt 1 ]
@@ -48,9 +43,10 @@ fi
 [[ "$outputdir" == "" ]] && echo "Error: No output path provided" && exit 1
 
 
+echo "all dir = ${inputdirs[*]}"
 
-
-for dir in $inputdirs; do
+for dir in ${inputdirs[*]}; do
+    echo "test dir $dir"
     if [ ! -d $dir ] ; then
       echo "Error: Directory not found : $dir" && exit 1
     fi
@@ -78,11 +74,10 @@ rm -rf $outputdir
 mkdir $outputdir
 
 filedir=$(dirname "$(readlink -f "$0")")
-homedir=$(dirname "filedir")
+homedir=$(dirname "$filedir")
 
 
-cd $filedir
-cd ..
+cd $homedir
 
 
 export SBT_OPTS="-Dlog4j.configurationFile=${filedir}/../conf/log4j2.xml"
